## These functions are used to calculate the inverse of a matrix. The inverse of
## the matrix is cached to reduce computation time.

## This function takes a single matrix as an argument and generates a list of 4
## objects. Each object is a function to be called by the function cacheSolve.

makeCacheMatrix <- function(x = matrix()) {
  m <- NULL
  set <- function(y) {
    x <<- y
    m <<- NULL
  }
  get <- function() x
  setinv <- function(solve) m <<- solve
  getinv <- function() m
  list(set = set, get = get,
       setinv = setinv,
       getinv = getinv)
}


## This function uses the functions in lists generated by makeCacheMatrix 
## function to calculate the inverse of the matrix, or returns a cached value
## for the inverse if it has been previously calculated.

cacheSolve <- function(x, ...) {
  m <- x$getinv()
  if(!is.null(m)) {
    message("getting cached data")
    return(m)
  }
  data <- x$get()
  m <- solve(data, ...)
  x$setinv(m)
  m
}
